import { useState } from 'react';
import { PageLayout } from '../components/Layout.jsx';
import { Shield, Trash2, Download, FolderOpen, Info } from 'lucide-react';

export default function Settings() {
  const [darkMode] = useState(() => localStorage.getItem('darkMode') === 'true');
  const [backendUrl, setBackendUrl] = useState('http://localhost:3001');
  const [saved, setSaved] = useState(false);

  const handleSave = () => {
    localStorage.setItem('backendUrl', backendUrl);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleReset = () => {
    if (window.confirm('Reset all local settings? This will not delete your workflow files.')) {
      localStorage.clear();
      window.location.reload();
    }
  };

  return (
    <PageLayout title="Settings" subtitle="Configuration and workspace settings">
      <div className="max-w-2xl space-y-6">

        {/* Backend */}
        <div className="card p-5">
          <div className="flex items-center gap-2 mb-4">
            <FolderOpen size={16} className="text-brand-500" />
            <h3 className="section-title text-sm">Backend Connection</h3>
          </div>
          <div className="space-y-3">
            <div>
              <label className="label">Backend URL</label>
              <input
                type="text"
                value={backendUrl}
                onChange={e => setBackendUrl(e.target.value)}
                className="input"
              />
              <p className="text-xs text-slate-400 mt-1">
                Start backend: <code className="bg-slate-100 dark:bg-slate-800 px-1 rounded">cd backend && npm install && npm run dev</code>
              </p>
            </div>
            <button onClick={handleSave} className="btn-primary text-xs">
              {saved ? 'Saved!' : 'Save'}
            </button>
          </div>
        </div>

        {/* Workflow location */}
        <div className="card p-5">
          <div className="flex items-center gap-2 mb-4">
            <FolderOpen size={16} className="text-slate-500" />
            <h3 className="section-title text-sm">Workflow Files Location</h3>
          </div>
          <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-3">
            <code className="text-xs font-mono text-slate-600 dark:text-slate-400">
              sales-agent-workflow/<br />
              ├── ICP.md<br />
              ├── LEADS.md<br />
              ├── LEADS.csv<br />
              └── companies/<br />
              &nbsp;&nbsp;&nbsp;&nbsp;└── [company-name]/<br />
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── COMPANY-RESEARCH.md<br />
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── OUTREACH-SEQUENCE.md<br />
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── ...
            </code>
          </div>
          <p className="text-xs text-slate-400 mt-2">
            These files are generated by Claude Code agents. The frontend reads them from this location.
          </p>
        </div>

        {/* Export */}
        <div className="card p-5">
          <div className="flex items-center gap-2 mb-4">
            <Download size={16} className="text-slate-500" />
            <h3 className="section-title text-sm">Export Options</h3>
          </div>
          <div className="space-y-2 text-xs text-slate-500 dark:text-slate-400">
            <p>Export buttons are available on the Lead Finder, Company Research, and Meeting Prep pages.</p>
            <p>Supported formats: <strong className="text-slate-700 dark:text-slate-300">Markdown (.md)</strong> and <strong className="text-slate-700 dark:text-slate-300">CSV (.csv)</strong></p>
          </div>
        </div>

        {/* Safe usage */}
        <div className="card p-5 border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-900/20">
          <div className="flex items-center gap-2 mb-4">
            <Shield size={16} className="text-amber-600 dark:text-amber-400" />
            <h3 className="text-sm font-semibold text-amber-800 dark:text-amber-300">Safe Usage Rules</h3>
          </div>
          <div className="space-y-2">
            {[
              'All data is sourced from public information only',
              'No private databases, paywalled sites, or login-gated pages are accessed',
              'Email addresses are only listed if found on a public company page',
              'Outreach content is professional, personalized, and respectful — no spam',
              'Facts are always separated from assumptions with confidence levels',
              'Source links are provided for every fact',
              'No fabricated case studies, testimonials, or results are generated',
            ].map((rule, i) => (
              <div key={i} className="flex gap-2">
                <span className="text-amber-500 flex-shrink-0">✓</span>
                <span className="text-xs text-amber-700 dark:text-amber-400">{rule}</span>
              </div>
            ))}
          </div>
        </div>

        {/* API Keys */}
        <div className="card p-5">
          <div className="flex items-center gap-2 mb-4">
            <Info size={16} className="text-slate-500" />
            <h3 className="section-title text-sm">API Keys (Placeholder)</h3>
          </div>
          <div className="space-y-3">
            {['ANTHROPIC_API_KEY', 'OPENAI_API_KEY'].map(key => (
              <div key={key}>
                <label className="label">{key}</label>
                <input type="password" placeholder="Not required — agents run through Claude Code" className="input opacity-50 cursor-not-allowed" disabled />
              </div>
            ))}
            <p className="text-xs text-slate-400">
              The sales agents run through Claude Code directly — no API key is needed in the frontend.
            </p>
          </div>
        </div>

        {/* Reset */}
        <div className="card p-5 border-red-200 dark:border-red-900">
          <div className="flex items-center gap-2 mb-4">
            <Trash2 size={16} className="text-red-500" />
            <h3 className="text-sm font-semibold text-red-600 dark:text-red-400">Reset Workspace</h3>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">
            Clears local browser settings only. Your workflow files in <code className="bg-slate-100 dark:bg-slate-800 px-1 rounded">sales-agent-workflow/</code> will not be deleted.
          </p>
          <button onClick={handleReset} className="inline-flex items-center gap-2 px-4 py-2 bg-red-50 dark:bg-red-900/20 hover:bg-red-100 dark:hover:bg-red-900/40 text-red-600 dark:text-red-400 text-sm font-medium rounded-lg transition-colors border border-red-200 dark:border-red-800">
            <Trash2 size={14} /> Reset Local Settings
          </button>
        </div>
      </div>
    </PageLayout>
  );
}
